/** Arabic strings for staff pages (review, editors, settings, admin). English text is the key. */
export const AR_STAFF = {
  '(last 90 days)': '(آخر 90 يومًا)',
  '(optional — you can add one later)': '(اختياري — يمكنك إضافته لاحقًا)',
  '. It starts automatically in the background.': '. يعمل تلقائيًا في الخلفية.',
  '0 = unlimited. Override per company below.': '0 = بلا حد. يمكن تعديله لكل شركة بالأسفل.',
  '1 — fastest': '1 — الأسرع',
  '1. Executive summary': '1. الملخص التنفيذي',
  '10+ characters with upper, lower case and a number.': '10 أحرف أو أكثر تشمل حرفًا كبيرًا وصغيرًا ورقمًا.',
  '2 — flags disagreements': '2 — ينبّه عند الاختلاف',
  '3 — median of three (slowest, steadiest)': '3 — الوسيط من ثلاث (الأبطأ والأثبت)',
  'AI draft grading': 'مسودة تصحيح بالذكاء الاصطناعي',
  'AI draft {n}': 'مسودة الذكاء الاصطناعي {n}',
  'AI draft · {c} confidence': 'مسودة الذكاء الاصطناعي · ثقة {c}',
  'AI draft: {score}/{max} · {c} confidence': 'مسودة الذكاء الاصطناعي: {score}/{max} · ثقة {c}',
  'AI drafts a grade for each submission against the rubric. Nothing reaches the employee until you approve it.': 'يقترح الذكاء الاصطناعي درجة لكل تسليم وفق معايير التقييم. لا يصل شيء للموظف قبل اعتمادك.',
  'AI drafts approved without changes': 'مسودات اعتُمدت دون تعديل',
  'AI grading, file size limits, storage per customer and notification emails.': 'التصحيح بالذكاء الاصطناعي، وحدود حجم الملفات، والتخزين لكل عميل، وإشعارات البريد.',
  'AI model': 'نموذج الذكاء الاصطناعي',
  'AI {n}%': 'الذكاء الاصطناعي {n}%',
  'Accent colour': 'اللون المميز',
  'Accepted file types': 'أنواع الملفات المقبولة',
  'Add admin': 'إضافة مدير',
  "Add an instructor, then assign the courses they'll teach and grade.": 'أضف مدربًا ثم أسند إليه الدورات التي سيدرّسها ويصحّحها.',
  'Add employee': 'إضافة موظف',
  'Add milestone': 'إضافة مرحلة',
  'Add question': 'إضافة سؤال',
  'Add task': 'إضافة مهمة',
  'Add your first customer to start onboarding their employees.': 'أضف أول عميل لتبدأ تهيئة موظفيه.',
  'All caught up': 'لا شيء متبقٍ',
  'All channels': 'كل القنوات',
  'All courses': 'كل الدورات',
  'All requests': 'كل الطلبات',
  'Also included automatically': 'يُضاف تلقائيًا أيضًا',
  'Approve & send feedback': 'اعتماد وإرسال الملاحظات',
  'Approve anyway': 'اعتماد على أي حال',
  Approved: 'معتمد',
  'Approved {x} — the employee has the feedback.': 'اعتُمد {x} — وصلت الملاحظات للموظف.',
  Area: 'نقطة',
  'Areas to tighten up': 'نقاط للتحسين',
  'Ask my instructor': 'سؤال مدربي',
  'Assign this course': 'إسناد هذه الدورة',
  'Assigned courses': 'الدورات المسندة',
  Assignment: 'المهمة',
  'At least one attempt was submitted after the time limit': 'سُلّمت محاولة واحدة على الأقل بعد انتهاء الوقت',
  Attempted: 'حاولوا',
  Attempts: 'المحاولات',
  'Attempts allowed (0 = unlimited)': 'المحاولات المسموحة (0 = بلا حد)',
  'Automatic checks': 'الفحوص التلقائية',
  'Average best score': 'متوسط أفضل درجة',
  'Avg score': 'متوسط الدرجة',
  'Avg. first response': 'متوسط أول رد',
  'Back to assignment': 'العودة للمهمة',
  'Back to quiz': 'العودة للاختبار',
  'Based on each employee’s latest attempt. Questions most people miss are worth explaining again — or rewording.': 'بناءً على آخر محاولة لكل موظف. الأسئلة التي يخطئ فيها الأغلب تستحق شرحًا جديدًا أو إعادة صياغة.',
  Basics: 'الأساسيات',
  'Being drafted by AI': 'قيد التصحيح بالذكاء الاصطناعي',
  'Below pass': 'أقل من النجاح',
  Best: 'الأفضل',
  'Business value': 'القيمة للعمل',
  'Business value assessment': 'تقييم القيمة للعمل',
  By: 'بواسطة',
  'CV accomplishment': 'إنجاز للسيرة الذاتية',
  'Callout type': 'نوع الملاحظة',
  Cancel: 'إلغاء',
  Capstone: 'المشروع الختامي',
  'Certificate no.': 'رقم الشهادة',
  'Certificate not found': 'الشهادة غير موجودة',
  'Certificate verification': 'التحقق من الشهادة',
  'Certification mapping': 'الربط بالشهادات المهنية',
  Channel: 'القناة',
  'Checking the local AI…': 'جارٍ فحص الذكاء الاصطناعي المحلي…',
  'Checking…': 'جارٍ الفحص…',
  'Choose a course…': 'اختر دورة…',
  Close: 'إغلاق',
  'Closing line': 'جملة الختام',
  Code: 'الرمز',
  Company: 'الشركة',
  'Company admins': 'مديرو الشركة',
  'Company name': 'اسم الشركة',
  'Complete by (optional)': 'الإنجاز قبل (اختياري)',
  Copy: 'نسخ',
  'Correct answer': 'الإجابة الصحيحة',
  'Course questions': 'أسئلة الدورة',
  'Create a course first.': 'أنشئ دورة أولًا.',
  'Create account': 'إنشاء الحساب',
  'Create company': 'إنشاء الشركة',
  'Create course': 'إنشاء الدورة',
  'Create instructor': 'إنشاء المدرب',
  Criterion: 'المعيار',
  'Current milestone': 'المرحلة الحالية',
  "Customers, the seats they've purchased, and their admins.": 'العملاء والمقاعد التي اشتروها ومديروهم.',
  'Default storage per company': 'التخزين الافتراضي لكل شركة',
  Delete: 'حذف',
  'Delete question': 'حذف السؤال',
  'Delete task': 'حذف المهمة',
  Details: 'التفاصيل',
  Discard: 'تجاهل',
  Done: 'تم',
  'Download and install Ollama for Windows from': 'نزّل Ollama لويندوز وثبّته من',
  'Draft PDF': 'مسودة PDF',
  'Draft saved {x}': 'حُفظت المسودة {x}',
  'Drafting…': 'جارٍ التصحيح…',
  'Drag items (or use the arrows) to reorder them or move them to another milestone. Publishing, duplicating and deleting apply straight away.': 'اسحب العناصر (أو استخدم الأسهم) لإعادة ترتيبها أو نقلها لمرحلة أخرى. النشر والنسخ والحذف تُطبَّق فورًا.',
  'Drop items here': 'أفلت العناصر هنا',
  'Drop templates, sample logs or pcaps here, or': 'أفلت القوالب أو السجلات أو ملفات pcap هنا، أو',
  Due: 'الاستحقاق',
  'Due date': 'تاريخ الاستحقاق',
  Duplicate: 'نسخ',
  'Each attempt shows them in a different order (scores are not affected)': 'تظهر بترتيب مختلف في كل محاولة (لا يؤثر على الدرجات)',
  'Edits are saved as a private draft. The employee only sees feedback after you approve or return it.': 'تُحفظ تعديلاتك كمسودة خاصة. لا يرى الموظف الملاحظات إلا بعد اعتمادها أو إعادتها.',
  'Email notifications to users': 'إشعارات البريد للمستخدمين',
  'Employee note': 'ملاحظة الموظف',
  'Employee seats purchased': 'مقاعد الموظفين المشتراة',
  'Employee submission — all files': 'تسليم الموظف — كل الملفات',
  'Employee submission — per file': 'تسليم الموظف — لكل ملف',
  'Empty milestones are kept — remove them with the bin icon if you don’t need them.': 'تبقى المراحل الفارغة — احذفها بأيقونة السلة إن لم تحتجها.',
  Enrolled: 'المسجّلون',
  Everyone: 'الجميع',
  'Evidence the AI found in the submission': 'أدلة وجدها الذكاء الاصطناعي في التسليم',
  'Executive summary': 'الملخص التنفيذي',
  'Explanation shown after submitting (optional)': 'شرح يظهر بعد الإرسال (اختياري)',
  'Feedback PDF': 'ملاحظات PDF',
  'Feedback isn’t ready yet': 'الملاحظات ليست جاهزة بعد',
  'File size limits': 'حدود حجم الملفات',
  Files: 'الملفات',
  Filter: 'تصفية',
  'Filter by status': 'تصفية حسب الحالة',
  'Final grade': 'الدرجة النهائية',
  'First company admin': 'أول مدير للشركة',
  From: 'من',
  Full: 'ممتلئة',
  'Generate an on-the-job training progress report for any employee in this course.': 'أنشئ تقرير تقدّم للتدريب على رأس العمل لأي موظف في هذه الدورة.',
  Grade: 'الدرجة',
  'Grade & feedback': 'الدرجة والملاحظات',
  'Grade manually': 'صحّح يدويًا',
  'Graded deliverables': 'الأعمال المُقيَّمة',
  'Grader guidance: what excellent vs weak work looks like (optional)': 'إرشاد للمصحح: كيف يبدو العمل الممتاز مقابل الضعيف (اختياري)',
  'Grades, new courses, support replies, review queue, team updates. Each person can still turn categories off in their account settings.': 'الدرجات والدورات الجديدة وردود الدعم وقائمة التصحيح وتحديثات الفريق. يستطيع كل شخص إيقاف ما لا يريده من إعدادات حسابه.',
  'Grading breakdown': 'تفاصيل التقييم',
  'Grading criteria': 'معايير التقييم',
  'Grading engine': 'محرك التصحيح',
  'Has work waiting for grading': 'لديه أعمال بانتظار التصحيح',
  'Hex colour': 'رمز اللون',
  'Hide details': 'إخفاء التفاصيل',
  High: 'عالية',
  'High — it’s blocking my work': 'عالية — توقف عملي',
  Hours: 'الساعات',
  'In-house model': 'نموذج داخلي',
  Inactive: 'غير نشط',
  'Instructions (optional)': 'التعليمات (اختياري)',
  'Instructor resources — per file': 'ملفات المدرب — لكل ملف',
  Issue: 'المشكلة',
  Issued: 'تاريخ الإصدار',
  'Issued by': 'صادرة عن',
  'Items that already have submissions or quiz attempts can’t be deleted — unpublish them instead so employees’ grades are kept.': 'لا يمكن حذف العناصر التي لها تسليمات أو محاولات — ألغِ نشرها بدلًا من ذلك لتبقى درجات الموظفين.',
  'Job-description requirement this proves (for progress reports)': 'متطلب الوصف الوظيفي الذي تثبته (لتقارير التقدّم)',
  'Keep editing': 'متابعة التعديل',
  Kind: 'النوع',
  Lab: 'معمل',
  'Last activity': 'آخر نشاط',
  'Last attempt': 'آخر محاولة',
  'Learn from instructors': 'التعلّم من المدربين',
  'Leave a blank line between paragraphs.': 'اترك سطرًا فارغًا بين الفقرات.',
  'Lesson (video / reading — nothing to submit)': 'درس (فيديو / قراءة — لا يوجد تسليم)',
  'Lesson / video': 'درس / فيديو',
  'LinkedIn skills': 'مهارات LinkedIn',
  'Login, labs, uploads or anything technical': 'الدخول أو المعامل أو الرفع أو أي مشكلة تقنية',
  Logo: 'الشعار',
  'Logo and accent colour': 'الشعار واللون المميز',
  Low: 'منخفضة',
  'Low — whenever you can': 'منخفضة — عندما يتاح لك',
  'Lowercase letters, numbers and dashes.': 'حروف إنجليزية صغيرة وأرقام وشرطات.',
  'Mark resolved': 'تعليم كمحلول',
  'Max files': 'أقصى عدد ملفات',
  'Max size per file (MB)': 'أقصى حجم للملف (ميجابايت)',
  Medium: 'متوسطة',
  'Milestone completion': 'إنجاز المراحل',
  'Milestones (one per line)': 'المراحل (مرحلة في كل سطر)',
  Model: 'النموذج',
  'Move down': 'تحريك لأسفل',
  'Move milestone down': 'تحريك المرحلة لأسفل',
  'Move milestone up': 'تحريك المرحلة لأعلى',
  'Move up': 'تحريك لأعلى',
  Name: 'الاسم',
  'Need a reply': 'تحتاج ردًا',
  'New company': 'شركة جديدة',
  'New customer company': 'شركة عميل جديدة',
  'New employee': 'موظف جديد',
  'New instructor': 'مدرب جديد',
  'New request': 'طلب جديد',
  'Next steps': 'الخطوات التالية',
  'Next steps & reporting cadence': 'الخطوات التالية ومواعيد التقارير',
  'No AI draft for this submission — fill in the scores and feedback below.': 'لا توجد مسودة لهذا التسليم — أدخل الدرجات والملاحظات بالأسفل.',
  'No AI draft yet.': 'لا توجد مسودة بعد.',
  'No AI draft — grade this one yourself': 'لا توجد مسودة — صحّح هذا التسليم بنفسك',
  'No approved AI-drafted submissions yet. This fills in as instructors approve grades.': 'لا توجد تسليمات معتمدة من مسودات الذكاء الاصطناعي بعد. يمتلئ هذا مع اعتماد المدربين للدرجات.',
  'No backlog — every submission has been reviewed.': 'لا يوجد تراكم — كل التسليمات رُوجعت.',
  'No companies yet': 'لا توجد شركات بعد',
  'No course assigned': 'لم تُسند دورة',
  'No email server yet. Add SMTP_HOST, SMTP_USER, SMTP_PASS and MAIL_FROM to the server .env — until then emails are only logged in the server console.': 'لا يوجد خادم بريد بعد. أضف SMTP_HOST وSMTP_USER وSMTP_PASS وMAIL_FROM إلى ملف ‎.env‎ في الخادم — وحتى ذلك الحين تُسجَّل الرسائل في سجل الخادم فقط.',
  'No employees are enrolled in this course yet.': 'لا يوجد موظفون مسجّلون في هذه الدورة بعد.',
  'No employees match this view.': 'لا يوجد موظفون يطابقون هذا العرض.',
  'No employees yet. Add your first employee to start their onboarding.': 'لا يوجد موظفون بعد. أضف أول موظف لتبدأ تهيئته.',
  'No instructors yet': 'لا يوجد مدربون بعد',
  'No logo yet': 'لا يوجد شعار بعد',
  'No matches': 'لا نتائج',
  'No submissions in this list.': 'لا توجد تسليمات في هذه القائمة.',
  'No warnings — the AI quoted the submission for every score.': 'لا تحذيرات — استشهد الذكاء الاصطناعي بالتسليم لكل درجة.',
  'Nobody is enrolled yet.': 'لا أحد مسجّل بعد.',
  'None assigned': 'لا شيء مُسند',
  'None yet': 'لا شيء بعد',
  Normal: 'عادية',
  'Not assigned': 'غير مُسند',
  'Not installed yet — run': 'غير مثبّت بعد — شغّل',
  'Not passed yet': 'لم ينجح بعد',
  'Not saved': 'لم يُحفظ',
  'Note, e.g. “Watch before Task 2” (optional)': 'ملاحظة، مثل «شاهده قبل المهمة 2» (اختياري)',
  Notes: 'ملاحظات',
  'Notes (short, e.g. “Accurate hierarchy; missing description”)': 'ملاحظات (قصيرة، مثل «تسلسل صحيح؛ ينقصه الوصف»)',
  'Nothing here': 'لا شيء هنا',
  'Nothing waiting. New submissions show up here as soon as the AI draft is ready.': 'لا شيء بالانتظار. تظهر التسليمات الجديدة هنا فور جاهزية المسودة.',
  'An administrator hasn’t assigned you to a course yet.': 'لم يسندك المدير إلى أي دورة بعد.',
  'Notification emails': 'رسائل الإشعارات',
  Number: 'الرقم',
  'Numbers, tables and charts come from the platform automatically. Adjust the wording below before downloading.': 'الأرقام والجداول والرسوم تأتي من المنصة تلقائيًا. عدّل الصياغة بالأسفل قبل التنزيل.',
  'Ollama is running at': 'Ollama يعمل على',
  'Ollama isn’t reachable at': 'تعذّر الوصول إلى Ollama على',
  'One correct answer': 'إجابة صحيحة واحدة',
  'One sentence verdict. Write the score as “{n}/100” — it is kept equal to the final total and shown in bold.': 'حكم في جملة واحدة. اكتب الدرجة بصيغة «{n}/100» — تبقى مساوية للدرجة النهائية وتظهر بخط عريض.',
  'Only do this when you’ve confirmed the request with the person (for example by phone). The action is recorded in the audit log.': 'لا تفعل ذلك إلا بعد التأكد من الطلب مع الشخص (بالهاتف مثلًا). يُسجَّل الإجراء في سجل التدقيق.',
  'Open the file': 'افتح الملف',
  'Open the submission': 'افتح التسليم',
  Option: 'خيار',
  'Optional quick test:': 'اختبار سريع اختياري:',
  Order: 'الترتيب',
  'Organise course': 'ترتيب الدورة',
  'Out of attempts': 'انتهت المحاولات',
  Overview: 'الملخص',
  'PDF/Word show the AI draft or the last approved version, not unsent edits.': 'ملفات PDF/Word تعرض المسودة أو آخر نسخة معتمدة، وليس التعديلات غير المرسلة.',
  'PNG or JPG, up to 1 MB. A wide logo on a transparent background works best.': 'PNG أو JPG حتى 1 ميجابايت. يُفضّل شعار عريض بخلفية شفافة.',
  'Pass mark (%)': 'درجة النجاح (%)',
  'Pass mark {n}': 'درجة النجاح {n}',
  'Password-reset emails are always sent, whatever this switch says.': 'رسائل إعادة تعيين كلمة المرور تُرسل دائمًا بغض النظر عن هذا المفتاح.',
  'Paste a YouTube, Vimeo, Loom or Google Drive link, or a direct .mp4 link. Videos appear at the top of the brief.': 'الصق رابط YouTube أو Vimeo أو Loom أو Google Drive أو رابط mp4 مباشر. تظهر الفيديوهات أعلى الوصف.',
  'Per rubric criterion. Longer submissions are not cut: the AI reads the most relevant parts for each criterion. ~14 000 suits 7B models, ~10 000 suits 3B.': 'لكل معيار تقييم. لا تُقتطع التسليمات الطويلة: يقرأ الذكاء الاصطناعي أكثر الأجزاء صلة بكل معيار. ~14000 تناسب نماذج 7B و~10000 تناسب 3B.',
  'Pick a colour': 'اختر لونًا',
  'Platform (labs)': 'المنصة (المعامل)',
  'Platform settings': 'إعدادات المنصة',
  'Platform support': 'دعم المنصة',
  Point: 'نقطة',
  Points: 'النقاط',
  'Prepared for': 'أُعدّ لـ',
  Press: 'اضغط',
  Preview: 'معاينة',
  'Preview as employee': 'معاينة كموظف',
  'Preview — what employees will see': 'معاينة — ما سيراه الموظفون',
  Priority: 'الأولوية',
  'Professional development': 'التطوير المهني',
  Progress: 'التقدّم',
  Question: 'السؤال',
  'Question analysis': 'تحليل الأسئلة',
  'Question type': 'نوع السؤال',
  'Questions about course content, assignments or your grade': 'أسئلة عن محتوى الدورة أو المهام أو درجتك',
  Quota: 'الحصة',
  'Re-draft': 'إعادة الصياغة',
  'Re-draft with AI': 'إعادة التصحيح بالذكاء الاصطناعي',
  'Read-only': 'للقراءة فقط',
  Recommendation: 'التوصية',
  'Refresh status': 'تحديث الحالة',
  Remove: 'إزالة',
  'Remove callout': 'إزالة الملاحظة',
  'Remove criterion': 'إزالة المعيار',
  'Remove milestone': 'إزالة المرحلة',
  'Remove option': 'إزالة الخيار',
  'Remove point': 'إزالة النقطة',
  'Remove row': 'إزالة الصف',
  'Remove video': 'إزالة الفيديو',
  Reopen: 'إعادة فتح',
  Report: 'التقرير',
  'Report text': 'نص التقرير',
  Request: 'الطلب',
  'Reset password': 'إعادة تعيين كلمة المرور',
  Resolved: 'محلول',
  'Resources for employees': 'ملفات للموظفين',
  'Retry AI': 'إعادة المحاولة بالذكاء الاصطناعي',
  Return: 'إعادة',
  'Return for rework': 'إعادة للتعديل',
  Review: 'مراجعة',
  'Review & grade': 'مراجعة وتصحيح',
  Revoke: 'إلغاء',
  'Run the AI again (e.g. after changing the model or the rubric)': 'شغّل الذكاء الاصطناعي مرة أخرى (مثلًا بعد تغيير النموذج أو المعايير)',
  'Runs per criterion': 'مرات التشغيل لكل معيار',
  Save: 'حفظ',
  'Save assignments': 'حفظ المهام',
  'Save colour': 'حفظ اللون',
  'Save quiz': 'حفظ الاختبار',
  'Save the assignment first, then add files here.': 'احفظ المهمة أولًا ثم أضف الملفات هنا.',
  'Save this version and share it with the company admin': 'احفظ هذه النسخة وشاركها مع مدير الشركة',
  Score: 'الدرجة',
  'Score %': 'الدرجة %',
  'Score for {x}': 'درجة {x}',
  'Search by employee or course': 'ابحث بالموظف أو الدورة',
  'Search by name, email or department': 'ابحث بالاسم أو البريد أو القسم',
  'Search employees': 'ابحث عن موظف',
  'Search name or assignment': 'ابحث بالاسم أو المهمة',
  'Search reports': 'ابحث في التقارير',
  'Seat limit': 'حد المقاعد',
  'Seats used': 'المقاعد المستخدمة',
  Send: 'إرسال',
  'Send request': 'إرسال الطلب',
  'Set up the in-house model (one time, free)': 'إعداد النموذج الداخلي (مرة واحدة، مجانًا)',
  'Several correct answers': 'عدة إجابات صحيحة',
  Shared: 'تمت المشاركة',
  'Short ID': 'معرّف قصير',
  'Show details': 'عرض التفاصيل',
  'Show the model how instructors graded earlier submissions of the same assignment (and where the AI was too generous or too harsh).': 'اعرض على النموذج كيف صحّح المدربون تسليمات سابقة لنفس المهمة (وأين كان الذكاء الاصطناعي متساهلًا أو متشددًا).',
  'Solid work overall — …': 'عمل جيد بشكل عام — …',
  'Start here — the total and the overview follow these scores.': 'ابدأ هنا — الإجمالي والملخص يتبعان هذه الدرجات.',
  'Storage by company': 'التخزين حسب الشركة',
  Strength: 'نقطة قوة',
  Strengths: 'نقاط القوة',
  Student: 'الطالب',
  Subject: 'الموضوع',
  Submission: 'التسليم',
  Submissions: 'التسليمات',
  Submitted: 'تم التسليم',
  Suggestion: 'الاقتراح',
  Summary: 'الملخص',
  'Templates, sample logs, pcaps or reading material employees download from the assignment page. Uploaded straight away — no need to press Save.': 'قوالب أو سجلات أو ملفات pcap أو مواد قراءة ينزّلها الموظفون من صفحة المهمة. تُرفع فورًا — لا حاجة للضغط على حفظ.',
  'Text sent to the model': 'النص المرسل للنموذج',
  'The AI gave {n}% without quoting the submission — check this one.': 'أعطى الذكاء الاصطناعي {n}% دون اقتباس من التسليم — راجع هذا المعيار.',
  'The AI grader scores each criterion against this rubric. Guidance is only visible to graders.': 'يقيّم الذكاء الاصطناعي كل معيار وفق هذه المعايير. الإرشادات تظهر للمصححين فقط.',
  'The AI is drafting this grade — the page updates by itself. You can read the submission meanwhile.': 'يصحّح الذكاء الاصطناعي هذا التسليم — تتحدث الصفحة تلقائيًا. يمكنك قراءة التسليم في الأثناء.',
  'The AI only drafts a grade. An instructor always reviews, edits and approves before an employee sees anything.': 'الذكاء الاصطناعي يقترح الدرجة فقط. يراجعها المدرب ويعدّلها ويعتمدها دائمًا قبل أن يرى الموظف أي شيء.',
  'The checks found serious problems and you haven’t opened the file yet. Approve anyway?': 'وجدت الفحوص مشكلات جدية ولم تفتح الملف بعد. هل تعتمد على أي حال؟',
  'The course starts as a draft. Assign instructors under Instructors, then publish it when the assignments are ready.': 'تبدأ الدورة كمسودة. عيّن المدربين من صفحة المدربين ثم انشرها عند جاهزية المهام.',
  'The employee will see your feedback and must resubmit. Make sure “Areas to tighten up” says what to fix.': 'سيرى الموظف ملاحظاتك وعليه إعادة التسليم. تأكد أن «نقاط للتحسين» توضح ما يجب إصلاحه.',
  'The link works once. Closing this window won’t show it again — reset again if it gets lost.': 'الرابط يعمل مرة واحدة. لن يظهر مرة أخرى بعد إغلاق النافذة — أعد التعيين إذا ضاع.',
  'The server accepts at most': 'يقبل الخادم بحد أقصى',
  'Their current password stops working immediately.': 'تتوقف كلمة مروره الحالية عن العمل فورًا.',
  "They'll be able to add employee accounts (up to the seat limit) and assign courses.": 'سيتمكن من إضافة حسابات الموظفين (حتى حد المقاعد) وإسناد الدورات.',
  'They’re signed out of every device.': 'يُسجَّل خروجه من كل الأجهزة.',
  'This document is empty.': 'هذا المستند فارغ.',
  'This verification code doesn’t match any certificate. Check the link or ask the holder for a new copy.': 'رمز التحقق لا يطابق أي شهادة. تحقق من الرابط أو اطلب نسخة جديدة من صاحبها.',
  'This video link isn’t valid.': 'رابط الفيديو غير صالح.',
  'Time limit (minutes, empty = none)': 'الوقت المحدد (بالدقائق، فارغ = بلا حد)',
  'Tip / hint / example': 'نصيحة / تلميح / مثال',
  Title: 'العنوان',
  'Title (optional)': 'العنوان (اختياري)',
  Today: 'اليوم',
  Topic: 'الموضوع',
  'True / False': 'صح / خطأ',
  'Try a different name or course.': 'جرّب اسمًا أو دورة أخرى.',
  'Unpublish instead': 'إلغاء النشر بدلًا من ذلك',
  'Unsaved changes': 'تغييرات غير محفوظة',
  Urgency: 'الأهمية',
  Urgent: 'عاجل',
  'Use default': 'استخدام الافتراضي',
  Used: 'المستخدم',
  'Video link': 'رابط الفيديو',
  'Video note': 'ملاحظة الفيديو',
  'Video title': 'عنوان الفيديو',
  'View files': 'عرض الملفات',
  'Visible to employees': 'ظاهر للموظفين',
  'Waiting for you': 'بانتظارك',
  'Waiting on customer': 'بانتظار العميل',
  Weeks: 'الأسابيع',
  Weight: 'الوزن',
  'Weight %': 'الوزن %',
  'What to check': 'ما يجب مراجعته',
  'What were you trying to do, what happened, and what have you tried?': 'ماذا كنت تحاول أن تفعل، وماذا حدث، وماذا جرّبت؟',
  'Written by the training team from your employee’s results. Reports your instructor shares with you appear under': 'يكتبها فريق التدريب من نتائج موظفك. تظهر التقارير التي يشاركها المدرب معك تحت',
  You: 'أنت',
  'You changed the AI score': 'غيّرت درجة الذكاء الاصطناعي',
  'You get a one-time link (valid 24 hours) so they can choose a new password. You never see it.': 'تحصل على رابط لمرة واحدة (صالح 24 ساعة) ليختار كلمة مرور جديدة. لن ترى كلمة المرور أبدًا.',
  'Your edits save automatically': 'تُحفظ تعديلاتك تلقائيًا',
  'Your instructor is still reviewing this submission.': 'ما زال مدربك يراجع هذا التسليم.',
  'Your logo and colour appear for your admins and employees, and on their certificates and exported reports.': 'يظهر شعارك ولونك لمديريك وموظفيك وعلى شهاداتهم والتقارير المصدّرة.',
  'Your new order and milestone changes haven’t been saved.': 'لم يُحفظ الترتيب الجديد وتغييرات المراحل.',
  'Your team. Each instructor only sees, edits and grades the courses you assign here.': 'فريقك. يرى كل مدرب ويعدّل ويصحّح الدورات التي تسندها إليه هنا فقط.',
  'and its attached files will be removed permanently.': 'وستُحذف ملفاته المرفقة نهائيًا.',
  'approved without edits': 'اعتُمدت دون تعديل',
  'attempt {n}': 'المحاولة {n}',
  'average difference (points)': 'متوسط الفرق (نقاط)',
  'average drafting time': 'متوسط وقت التصحيح',
  'average grade': 'متوسط الدرجة',
  chars: 'حرف',
  complete: 'مكتمل',
  completed: 'مكتملة',
  correct: 'صحيحة',
  'drafts approved': 'مسودات معتمدة',
  'e.g. Can’t filter Level 12+ alerts in W-01 Task 3': 'مثال: لا أستطيع تصفية تنبيهات المستوى 12+ في W-01 المهمة 3',
  edited: 'معدّل',
  high: 'عالية',
  low: 'منخفضة',
  'in the server .env). Instructors can set a different per-file limit on an individual assignment.': 'في ملف ‎.env‎ للخادم). يمكن للمدربين تحديد حد مختلف لكل مهمة.',
  'on the review page.': 'في صفحة المراجعة.',
  'or pick an installed one:': 'أو اختر نموذجًا مثبّتًا:',
  pts: 'نقطة',
  'seats in use': 'مقاعد مستخدمة',
  'waiting {x}': 'ينتظر {x}',
  'weight {n}%': 'الوزن {n}%',
  'within 5 points': 'في حدود 5 نقاط',
  '{name}’s submission is being re-drafted. It will be back in “Needs review” in a minute or two.': 'يُعاد تصحيح تسليم {name}. سيعود إلى «يحتاج مراجعة» خلال دقيقة أو اثنتين.',
  '{n} thing(s) to check': '{n} أمور للمراجعة',
  '— install and start it (steps below).': '— ثبّته وشغّله (الخطوات بالأسفل).',
  'New password': 'كلمة المرور الجديدة',
  'Repeat new password': 'أعد كتابة كلمة المرور الجديدة',
  'Temporary password': 'كلمة المرور المؤقتة',
  MB: 'ميجابايت',
  'Weeks 1–2': 'الأسبوعان 1–2',
  Password: 'كلمة المرور',
  'A criterion scored 50%+ but the AI could not quote supporting text from the submission.': 'حصل معيار على 50% أو أكثر لكن الذكاء الاصطناعي لم يستطع الاقتباس من التسليم لدعمه.',
  'The AI quoted text that is not in the submission. The quote was removed; check that criterion.': 'اقتبس الذكاء الاصطناعي نصًا غير موجود في التسليم. حُذف الاقتباس؛ راجع ذلك المعيار.',
  'Repeated AI runs disagreed by more than 15 points.': 'اختلفت مرات التشغيل المتكررة بأكثر من 15 نقطة.',
  'The model skipped or renamed a rubric criterion — those scores need you.': 'تخطّى النموذج معيارًا أو غيّر اسمه — هذه الدرجات تحتاجك.',
  'Very little text': 'نص قليل جدًا', 'Unreadable file': 'ملف غير مقروء', 'Scanned PDF or screenshots': 'PDF ممسوح أو صور شاشة', 'Text read from images (OCR)': 'نص مقروء من الصور (OCR)',
  'Tries to instruct the AI': 'يحاول توجيه الذكاء الاصطناعي', 'Tasks possibly missing': 'مهام قد تكون ناقصة', 'Copied from the brief': 'منسوخ من وصف المهمة', 'Similar to a colleague': 'مشابه لزميل', 'Long submission': 'تسليم طويل',
  'Score without evidence': 'درجة بلا دليل', 'Invented quote removed': 'حُذف اقتباس غير موجود', 'AI runs disagreed': 'اختلفت نتائج التشغيل', 'AI answer incomplete': 'إجابة الذكاء الاصطناعي ناقصة',
  'Every score is backed by quotes from the submission and the checks found nothing unusual.': 'كل درجة مدعومة باقتباسات من التسليم ولم تجد الفحوص شيئًا غير عادي.',
  'Mostly backed by quotes — skim the criteria marked below.': 'مدعومة بالاقتباسات في الغالب — راجع سريعًا المعايير المعلَّمة بالأسفل.',
  'Several scores lack evidence or the file was hard to read. Check the submission before approving.': 'عدة درجات بلا أدلة أو كان الملف صعب القراءة. راجع التسليم قبل الاعتماد.',
  'Open the submission': 'افتح التسليم',
  'Drafting…': 'جارٍ التصحيح…',
  'Open an employee’s progress report and choose “Share with company”.': 'افتح تقرير تقدّم موظف واختر «مشاركة مع الشركة».',
  'You’ll get a notification when your instructor shares one.': 'سيصلك إشعار عندما يشارك المدرب تقريرًا.',
  Active: 'نشط',
  'Add more details or reply…': 'أضف تفاصيل أو اكتب ردًا…',
  'All reports for this course': 'كل تقارير هذه الدورة',
  Deactivate: 'تعطيل',
  'Edit assignment': 'تعديل المهمة',
  'Hidden (draft) — click to publish': 'مخفي (مسودة) — اضغط للنشر',
  'How close are AI drafts to instructors’ final grades?': 'ما مدى قرب مسودات الذكاء الاصطناعي من درجات المدربين النهائية؟',
  'In-house (free)': 'داخلي (مجاني)',
  'Move or delete its items first': 'انقل عناصرها أو احذفها أولًا',
  'New assignment': 'مهمة جديدة',
  'New milestone quiz': 'اختبار مرحلة جديد',
  'New questions will show up here.': 'ستظهر الأسئلة الجديدة هنا.',
  'No requests yet': 'لا توجد طلبات بعد',
  'Nothing waiting': 'لا شيء بالانتظار',
  'Off — manual only': 'متوقف — يدوي فقط',
  'Official progress reports shared by your training team. Each one is a signed-off snapshot — download it as PDF to forward or file.': 'تقارير تقدّم رسمية يشاركها فريق التدريب. كل تقرير نسخة معتمدة — نزّله بصيغة PDF لإرساله أو حفظه.',
  'Open PowerShell and download the model (once):': 'افتح PowerShell ونزّل النموذج (مرة واحدة):',
  Reactivate: 'إعادة التفعيل',
  'Replace logo': 'استبدال الشعار',
  'Reports you and other instructors have shared with customer companies.': 'التقارير التي شاركتها أنت والمدربون الآخرون مع الشركات العميلة.',
  'Resetting…': 'جارٍ إعادة التعيين…',
  'Save AI settings': 'حفظ إعدادات الذكاء الاصطناعي',
  'Save assignment': 'حفظ المهمة',
  'Save limits': 'حفظ الحدود',
  'Suggested models:': 'نماذج مقترحة:',
  'This certificate was revoked': 'أُلغيت هذه الشهادة',
  'Upload logo': 'رفع الشعار',
  'Valid certificate': 'شهادة صالحة',
  'Visible to employees — click to hide': 'ظاهر للموظفين — اضغط للإخفاء',
  'When you need help, open a request — you’ll get a reply right here.': 'عندما تحتاج مساعدة افتح طلبًا — وسيصلك الرد هنا.',
  'Write your answer…': 'اكتب إجابتك…',
  'above. New submissions are then drafted automatically; for older ones use': 'بالأعلى. بعدها تُصحَّح التسليمات الجديدة تلقائيًا؛ وللقديمة استخدم',
  'per file': 'لكل ملف',
  '{n} model(s) installed': '{n} نموذج مثبّت',
  'Recommended for a 4–8 GB graphics card · ~4.7 GB': 'موصى به لكرت شاشة 4–8 جيجابايت · ~4.7 جيجابايت',
  'Alternative · ~4.9 GB': 'بديل · ~4.9 جيجابايت',
  'Faster, weaker — for machines without a graphics card · ~1.9 GB': 'أسرع وأضعف — للأجهزة بلا كرت شاشة · ~1.9 جيجابايت',
  'Better quality — needs 12 GB+ graphics memory · ~9 GB': 'جودة أعلى — يحتاج ذاكرة رسوميات 12 جيجابايت+ · ~9 جيجابايت',
  'Student questions': 'أسئلة الموظفين',
  'Every request on the platform — company admins and employees, plus the questions instructors are handling.': 'كل الطلبات على المنصة — من مديري الشركات والموظفين، بالإضافة إلى الأسئلة التي يتولاها المدربون.',
  'Questions from employees in the courses you teach.': 'أسئلة الموظفين في الدورات التي تدرّسها.',
  'Contact our team about accounts, seats, labs or anything else.': 'تواصل مع فريقنا بخصوص الحسابات أو المقاعد أو المعامل أو أي شيء آخر.',
  'Ask your instructor about the course, or contact platform support for technical help.': 'اسأل مدربك عن الدورة، أو تواصل مع دعم المنصة للمساعدة التقنية.',
  All: 'الكل',
  '{a}/{b} graded': '{a}/{b} مصحّح',
  '{n} waiting for grading': '{n} بانتظار التصحيح',
  '{n} report(s)': '{n} تقرير',
  'Criterion left for you': 'معيار متروك لك',
  'Feedback text not written': 'لم تُكتب الملاحظات',
  'The model got stuck on a criterion (it is scored 0) — score it yourself.': 'تعثّر النموذج في معيار (درجته 0) — قيّمه بنفسك.',
  'The scores are drafted but the model could not write the feedback text — write the overview yourself.': 'الدرجات جاهزة لكن النموذج لم يستطع كتابة الملاحظات — اكتب الملخص بنفسك.',
  'The AI could not grade this criterion — please score it yourself.': 'لم يستطع الذكاء الاصطناعي تقييم هذا المعيار — قيّمه بنفسك.',
  // queue / review extras
  Waiting: 'بانتظار',
  'Needs review': 'يحتاج مراجعة',
  Returned: 'مُعاد',
  'Being graded by AI': 'قيد التصحيح بالذكاء الاصطناعي',
  'Drop files here or browse': 'اسحب الملفات هنا أو تصفّح',
  'Reply': 'الرد',
  'Reply to reopen this request': 'ردّ لإعادة فتح الطلب',
  'Waiting for support': 'بانتظار الدعم',
  Replied: 'تم الرد',
  'General question': 'سؤال عام',
  'About an assignment': 'عن مهمة',
  'Grade or feedback': 'الدرجة أو الملاحظات',
  'Technical problem (lab, upload, access)': 'مشكلة تقنية (معمل، رفع، دخول)',
  'Account & access': 'الحساب والدخول',
  'Licences & seats': 'التراخيص والمقاعد',
  Other: 'أخرى',
  'Platform admin': 'مدير المنصة',
  'AI grading': 'التصحيح بالذكاء الاصطناعي',
};
