/**
 * Arabic UI strings. The English text is the key (see lib/i18n.jsx) — anything missing here shows in English.
 * Numbers and dates keep Western digits so scores stay easy to compare.
 */
export const AR = {
  // ── Navigation & shell
  Dashboard: 'الرئيسية',
  Companies: 'الشركات',
  Courses: 'الدورات',
  Instructors: 'المدربون',
  'Review queue': 'قائمة التصحيح',
  'Shared reports': 'التقارير المشتركة',
  Reports: 'التقارير',
  Support: 'الدعم',
  Questions: 'الأسئلة',
  Certificates: 'الشهادات',
  Settings: 'الإعدادات',
  'My courses': 'دوراتي',
  'Team progress': 'تقدّم الفريق',
  Employees: 'الموظفون',
  Branding: 'هوية الشركة',
  'My training': 'تدريبي',
  'Help & support': 'المساعدة والدعم',
  'Main navigation': 'القائمة الرئيسية',
  'Account settings': 'إعدادات الحساب',
  'Sign out': 'تسجيل الخروج',
  'Expand sidebar': 'توسيع القائمة',
  'Collapse sidebar': 'طيّ القائمة',
  'Open menu': 'فتح القائمة',
  '{n} waiting': '{n} بانتظارك',
  'Platform admin': 'مدير المنصة',
  'Company admin': 'مدير الشركة',
  Instructor: 'مدرب',
  Employee: 'موظف',

  // ── Notifications
  Notifications: 'الإشعارات',
  'Notifications, {n} unread': 'الإشعارات، {n} غير مقروءة',
  'Mark all read': 'تعليم الكل كمقروء',
  'Mark {n} read': 'تعليم {n} كمقروء',
  '{n} new': '{n} جديد',
  'What’s new': 'الجديد',
  'Nothing new yet. Updates about grades, courses and support replies show up here.': 'لا جديد حتى الآن. ستظهر هنا تحديثات الدرجات والدورات وردود الدعم.',
  '1 new reply': 'ردّ جديد',
  '{n} new replies': '{n} ردود جديدة',

  // ── Auth
  'Sign in': 'تسجيل الدخول',
  'Signing in…': 'جارٍ تسجيل الدخول…',
  'Sign-in failed.': 'تعذّر تسجيل الدخول.',
  'Work email': 'البريد الإلكتروني للعمل',
  'Forgot password?': 'نسيت كلمة المرور؟',
  'Remember me for 30 days': 'تذكّرني لمدة 30 يومًا',
  'Only tick “remember me” on your own device.': 'فعّل «تذكّرني» على جهازك الشخصي فقط.',
  'Use the account your company created for you.': 'استخدم الحساب الذي أنشأته شركتك لك.',
  'Your first weeks, one clear path.': 'أسابيعك الأولى، في مسار واحد واضح.',
  'See exactly what to finish, submit your work, and get reviewed feedback from your instructor.': 'اعرف بالضبط ما عليك إنجازه، وسلّم عملك، واحصل على ملاحظات مراجَعة من مدربك.',
  'Employee training for security teams': 'تدريب الموظفين لفرق الأمن',
  'Show password': 'إظهار كلمة المرور',
  'Hide password': 'إخفاء كلمة المرور',
  'Reset your password': 'إعادة تعيين كلمة المرور',
  'Enter your work email and we’ll send you a link to choose a new password.': 'أدخل بريد العمل وسنرسل لك رابطًا لاختيار كلمة مرور جديدة.',
  'Send reset link': 'إرسال رابط إعادة التعيين',
  'Sending…': 'جارٍ الإرسال…',
  'Check your email': 'تحقّق من بريدك',
  'If an account exists for {email}, we’ve sent a link to reset your password. It works once and expires in 30 minutes.': 'إذا كان هناك حساب مرتبط بـ {email} فقد أرسلنا رابطًا لإعادة تعيين كلمة المرور. يعمل الرابط مرة واحدة وتنتهي صلاحيته خلال 30 دقيقة.',
  'No email after a few minutes? Check spam, or ask your company admin to send you a reset link.': 'لم يصلك البريد بعد دقائق؟ راجع مجلد الرسائل غير المرغوبة، أو اطلب من مدير شركتك إرسال رابط إعادة التعيين.',
  'Back to sign in': 'العودة لتسجيل الدخول',
  'Choose a new password': 'اختر كلمة مرور جديدة',
  'For {email}': 'للحساب {email}',
  'Save new password': 'حفظ كلمة المرور الجديدة',
  'The two passwords don’t match.': 'كلمتا المرور غير متطابقتين.',
  'This link doesn’t work anymore': 'هذا الرابط لم يعد صالحًا',
  'Request a new link': 'طلب رابط جديد',
  'You’ll be signed out of every other device.': 'سيتم تسجيل خروجك من جميع الأجهزة الأخرى.',
  'Your account was set up with a temporary password. Choose your own to continue — nobody else will know it.': 'أُنشئ حسابك بكلمة مرور مؤقتة. اختر كلمة مرورك الخاصة للمتابعة — لن يعرفها أحد غيرك.',
  'Save and continue': 'حفظ ومتابعة',
  'Saving…': 'جارٍ الحفظ…',

  // ── Dashboard
  'Welcome, {name}': 'أهلًا، {name}',
  'Good morning': 'صباح الخير',
  'Good afternoon': 'مساء الخير',
  'Good evening': 'مساء الخير',
  ', ': '، ',
  'Loading dashboard': 'جارٍ تحميل لوحة المتابعة',
  'View all': 'عرض الكل',
  'No graded work yet': 'لا توجد أعمال مصحّحة بعد',
  'out of 100': 'من 100',
  Strong: 'ممتاز',
  Pass: 'ناجح',
  'Below target': 'أقل من المطلوب',
  'AI couldn’t grade these': 'تعذّر على الذكاء الاصطناعي تصحيحها',
  'No one is behind right now.': 'لا يوجد أحد متأخر الآن.',
  'Everyone is on track.': 'الجميع يسير وفق الخطة.',
  'No replies in 30 days': 'لا ردود منذ 30 يومًا',
  'Unanswered > 24 h': 'بلا رد منذ أكثر من 24 ساعة',
  'Your questions go straight to your course instructor.': 'تصل أسئلتك مباشرة إلى مدرب دورتك.',
  'Questions about seats, access or courses go to our team.': 'الأسئلة عن المقاعد أو الوصول أو الدورات تصل إلى فريقنا.',
  'Answer employees’ questions about your courses.': 'أجب عن أسئلة الموظفين حول دوراتك.',
  'Company and employee requests to the platform team.': 'طلبات الشركات والموظفين لفريق المنصة.',
  'Try again': 'حاول مرة أخرى',
  'Open dashboard': 'فتح لوحة المتابعة',
  '1 piece of work came back for rework — start there.': 'أُعيد إليك عمل واحد للتعديل — ابدأ به.',
  '{n} pieces of work came back for rework — start there.': 'أُعيدت إليك {n} أعمال للتعديل — ابدأ بها.',
  'You’re {pct}% through your training. Next up: {item}.': 'أنجزت {pct}% من تدريبك. التالي: {item}.',
  'You’re all caught up. Nice work.': 'أنجزت كل المطلوب. عمل رائع.',
  'You’re all caught up.': 'لا شيء متأخر.',
  'You haven’t been assigned a course yet.': 'لم تُسند إليك أي دورة بعد.',
  '{n} submission(s) waiting for your review.': '{n} تسليم بانتظار مراجعتك.',
  'Your review queue is empty.': 'قائمة التصحيح فارغة.',
  '{n} active employee(s), {pct}% average progress': '{n} موظف نشط، بمتوسط تقدّم {pct}%',
  '{n} submission(s) pending review across the platform, {m} open support request(s).': '{n} تسليم بانتظار المراجعة على المنصة، و{m} طلب دعم مفتوح.',
  ' — {n} need(s) attention': ' — {n} يحتاج متابعة',
  'Up next': 'التالي',
  'Needs your attention': 'يحتاج انتباهك',
  'Recent grades': 'أحدث الدرجات',
  'Latest graded work': 'أحدث الأعمال المصحّحة',
  'Progress by course': 'التقدّم حسب الدورة',
  'Employees who may need help': 'موظفون قد يحتاجون مساعدة',
  'Grading backlog by course': 'الأعمال المتراكمة حسب الدورة',
  'Submissions — last 14 days': 'التسليمات — آخر 14 يومًا',
  'Active employees': 'الموظفون النشطون',
  'Average grade': 'متوسط الدرجة',
  'Average progress': 'متوسط التقدّم',
  'Courses completed': 'دورات مكتملة',
  'Graded this week': 'صُحّح هذا الأسبوع',
  'Need attention': 'تحتاج متابعة',
  'Open questions': 'أسئلة مفتوحة',
  'Open support': 'طلبات دعم مفتوحة',
  'Overall progress': 'التقدّم الكلي',
  'Pending review': 'بانتظار المراجعة',
  'Published courses': 'الدورات المنشورة',
  'Reviewed this week': 'رُوجع هذا الأسبوع',
  'Graded work and feedback will appear here.': 'ستظهر هنا الأعمال المصحّحة والملاحظات.',
  'Grades appear here once an instructor approves them.': 'تظهر الدرجات هنا بعد أن يعتمدها المدرب.',
  'When your company assigns you a course it will appear here.': 'عندما تسند إليك شركتك دورة ستظهر هنا.',
  'Assign a course to your employees from the Courses page.': 'أسند دورة لموظفيك من صفحة الدورات.',
  'Your instructor asked for changes. Read the feedback, update your work and resubmit.': 'طلب مدربك تعديلات. اقرأ الملاحظات وحدّث عملك ثم أعد التسليم.',
  'You’re close to your limit — contact us through Support to add seats.': 'اقتربت من الحد الأقصى — تواصل معنا عبر الدعم لإضافة مقاعد.',
  '{n} days left': 'متبقٍ {n} أيام',
  '1 day left': 'متبقٍ يوم واحد',
  '{a}/{b} done': '{a}/{b} منجز',
  '{a} of {b} used': '{a} من {b} مستخدم',
  '{n} enrolled': '{n} مسجّل',
  '{n} open question(s)': '{n} سؤال مفتوح',
  '{n} open request(s)': '{n} طلب مفتوح',
  'Avg turnaround {x}': 'متوسط وقت التصحيح {x}',
  'Avg progress': 'متوسط التقدّم',
  'Avg grade': 'متوسط الدرجة',
  'AI draft': 'مسودة الذكاء الاصطناعي',
  'Needs action': 'يحتاج إجراء',
  Open: 'فتح',
  Oldest: 'الأقدم',
  'Now:': 'الآن:',
  'Get help': 'اطلب المساعدة',
  Seats: 'المقاعد',
  Waiting: 'بانتظار',
  Pending: 'معلّق',
  Complete: 'مكتمل',
  Item: 'العنصر',
  Course: 'الدورة',
  Status: 'الحالة',

  // ── Statuses
  'Not started': 'لم يبدأ',
  'Waiting for review': 'بانتظار المراجعة',
  'AI grading': 'يصحّحه الذكاء الاصطناعي',
  'AI draft ready': 'مسودة التصحيح جاهزة',
  'Needs manual grading': 'يحتاج تصحيحًا يدويًا',
  'Under review': 'قيد المراجعة',
  Graded: 'تم التصحيح',
  'Returned for rework': 'أُعيد للتعديل',
  Overdue: 'متأخر',
  Passed: 'ناجح',
  'Not passed': 'لم ينجح',
  Draft: 'مسودة',
  Published: 'منشورة',
  Revoked: 'ملغاة',
  late: 'متأخر',

  // ── Courses
  'These are the courses your company assigned to you.': 'هذه الدورات التي أسندتها إليك شركتك.',
  'The courses you teach and grade.': 'الدورات التي تدرّسها وتصحّحها.',
  'Courses available to your company. Open one to assign it to employees.': 'الدورات المتاحة لشركتك. افتح دورة لإسنادها للموظفين.',
  'Every course on the platform.': 'كل الدورات على المنصة.',
  'New course': 'دورة جديدة',
  'No courses yet': 'لا توجد دورات بعد',
  'Your manager hasn’t assigned a course to you yet.': 'لم يسند إليك مديرك أي دورة بعد.',
  'The platform admin hasn’t assigned you to a course yet.': 'لم يسندك مدير المنصة إلى أي دورة بعد.',
  'Create your first course to start building assignments.': 'أنشئ أول دورة لتبدأ في بناء المهام.',
  'No courses are available to your company yet.': 'لا توجد دورات متاحة لشركتك بعد.',
  '{a} of {b} graded': '{a} من {b} مصحّح',
  'Due {date}': 'الاستحقاق {date}',
  'Instructors: {names}': 'المدربون: {names}',
  'No instructor assigned': 'لم يُعيّن مدرب',
  'No instructor assigned yet — assign one under Instructors.': 'لم يُعيّن مدرب بعد — عيّن مدربًا من صفحة المدربين.',
  Unpublish: 'إلغاء النشر',
  'Publish course': 'نشر الدورة',
  Organise: 'ترتيب',
  'Progress reports': 'تقارير التقدّم',
  'Gradebook CSV': 'سجل الدرجات CSV',
  'Every employee × every graded item, as a spreadsheet': 'كل موظف × كل عنصر مُقيَّم، في جدول',
  'Assign to employees': 'إسناد للموظفين',
  'Draft — companies and employees can’t see this course until it’s published.': 'مسودة — لا يرى الشركات والموظفون هذه الدورة حتى تُنشر.',
  '{n} items': '{n} عناصر',
  Lesson: 'درس',
  'Includes video': 'يتضمن فيديو',
  '{n} resource file(s)': '{n} ملف مرجعي',
  Quiz: 'اختبار',
  '{n} questions': '{n} أسئلة',
  'Nothing here yet.': 'لا شيء هنا بعد.',

  // ── Assignment
  'Back to course': 'العودة للدورة',
  Edit: 'تعديل',
  Tasks: 'المهام',
  Tip: 'نصيحة',
  Hint: 'تلميح',
  Example: 'مثال',
  Warning: 'تحذير',
  Note: 'ملاحظة',
  Difficulty: 'الصعوبة',
  Type: 'النوع',
  'Estimated time': 'الوقت المتوقع',
  '{n} hours': '{n} ساعات',
  Platform: 'المنصة',
  Watch: 'شاهد',
  Videos: 'الفيديوهات',
  Video: 'فيديو',
  Scenario: 'السيناريو',
  Deliverable: 'المطلوب تسليمه',
  'How it’s graded': 'طريقة التقييم',
  'What you’ll be able to show': 'ما ستتمكن من إثباته',
  'Accepted files:': 'الملفات المقبولة:',
  'up to {n} file(s)': 'حتى {n} ملفات',
  'Submit your work': 'سلّم عملك',
  'Drop files here or': 'اسحب الملفات هنا أو',
  browse: 'تصفّح',
  'max {n} MB each': 'بحد أقصى {n} ميجابايت للملف',
  'over {n} MB': 'أكبر من {n} ميجابايت',
  'Remove {x}': 'إزالة {x}',
  Total: 'الإجمالي',
  '{a} of {b} MB': '{a} من {b} ميجابايت',
  'Remove or compress files over {n} MB (for example save the report as PDF, or zip screenshots).': 'احذف أو اضغط الملفات الأكبر من {n} ميجابايت (مثلًا احفظ التقرير بصيغة PDF أو اضغط لقطات الشاشة في ملف zip).',
  'Note to your instructor (optional)': 'ملاحظة لمدربك (اختياري)',
  'Uploading…': 'جارٍ الرفع…',
  'Submit for review': 'إرسال للمراجعة',
  'Only {x} files are accepted.': 'لا تُقبل إلا ملفات {x}.',
  'You can attach up to {n} file(s).': 'يمكنك إرفاق {n} ملفات كحد أقصى.',
  'Upload cancelled — nothing was submitted.': 'أُلغي الرفع — لم يُسلَّم شيء.',
  'Upload failed.': 'فشل الرفع.',
  'Your submissions': 'تسليماتك',
  'Attempt {n}': 'المحاولة {n}',
  'View {x}': 'عرض {x}',
  'Download {x}': 'تنزيل {x}',
  'View full feedback': 'عرض الملاحظات كاملة',
  'Your instructor is reviewing this. You’ll see the grade here once it’s approved.': 'يراجع مدربك هذا العمل. ستظهر الدرجة هنا بعد اعتمادها.',
  'Stuck on something?': 'متوقف عند شيء؟',
  'Ask your instructor — you’ll get a reply under Help & support.': 'اسأل مدربك — سيصلك الرد في صفحة المساعدة والدعم.',
  'Ask your instructor': 'اسأل مدربك',

  Resources: 'ملفات مرجعية',
  '{n} file(s)': '{n} ملف',
  Download: 'تنزيل',
  'Download failed.': 'فشل التنزيل.',
  'Could not open this file.': 'تعذّر فتح هذا الملف.',
  'Viewing {x}': 'عرض {x}',
  'Exit full screen': 'الخروج من ملء الشاشة',
  'Full screen': 'ملء الشاشة',
  'Close viewer': 'إغلاق العارض',
  'Loading file': 'جارٍ تحميل الملف',
  'Showing the first 500 rows — download for the rest.': 'تُعرض أول 500 صف — نزّل الملف لرؤية الباقي.',
  '…truncated — download for the full file': '…مقتطع — نزّل الملف كاملًا',
  'This file type can’t be shown in the browser.': 'لا يمكن عرض هذا النوع من الملفات في المتصفح.',
  Loading: 'جارٍ التحميل',
  'Loading page': 'جارٍ تحميل الصفحة',

  // ── Quiz
  'Milestone quiz': 'اختبار المرحلة',
  'pass mark {n}%': 'درجة النجاح {n}%',
  '{n} attempts': '{n} محاولات',
  '{n} min': '{n} دقيقة',
  Results: 'النتائج',
  'Edit quiz': 'تعديل الاختبار',
  'Passed. Nice work!': 'نجحت. أحسنت!',
  'Not passed yet (pass mark {n}%).': 'لم تنجح بعد (درجة النجاح {n}%).',
  '{a} of {b} points': '{a} من {b} نقطة',
  '{n} attempt(s) left': 'متبقٍ {n} محاولة',
  'Review the answers below.': 'راجع الإجابات بالأسفل.',
  'Your attempts:': 'محاولاتك:',
  'You’ve passed this quiz.': 'لقد نجحت في هذا الاختبار.',
  'No attempts left — ask your instructor under Help & support if you need another try.': 'لا توجد محاولات متبقية — اطلب من مدربك محاولة أخرى عبر المساعدة والدعم.',
  'This quiz is timed: {n} minutes.': 'هذا الاختبار محدد بوقت: {n} دقيقة.',
  'The timer starts when you press Start and keeps running if you leave the page. When time is up your answers are submitted automatically.': 'يبدأ المؤقت عند الضغط على «ابدأ» ويستمر حتى لو غادرت الصفحة. عند انتهاء الوقت تُرسل إجاباتك تلقائيًا.',
  'Start quiz': 'ابدأ الاختبار',
  'Select all that apply': 'اختر كل ما ينطبق',
  'Choose one': 'اختر إجابة واحدة',
  '{n} pt': '{n} نقطة',
  'Question {n}': 'السؤال {n}',
  'Why:': 'السبب:',
  '{a} of {b} answered': 'أُجيب {a} من {b}',
  'Submit answers': 'إرسال الإجابات',

  // ── Certificates
  'My certificates': 'شهاداتي',
  'Issued automatically when you complete every assignment and quiz of a course. Anyone can check them with the verification link.': 'تُصدر تلقائيًا عند إكمال كل مهام واختبارات الدورة. يمكن لأي شخص التحقق منها عبر رابط التحقق.',
  'Issued automatically when an employee completes every graded item of a course.': 'تُصدر تلقائيًا عندما يكمل الموظف كل العناصر المُقيَّمة في الدورة.',
  'No certificates yet — finish a course to earn one.': 'لا توجد شهادات بعد — أكمل دورة لتحصل على شهادة.',
  'No certificates issued yet.': 'لم تُصدر أي شهادات بعد.',
  'Certificate of completion': 'شهادة إتمام',
  'Aligned to {x}': 'متوافقة مع {x}',
  'Issued {date}': 'صدرت في {date}',
  'Average grade {n}%': 'متوسط الدرجة {n}%',
  'Download PDF': 'تنزيل PDF',
  Copied: 'تم النسخ',
  'Copy verification link': 'نسخ رابط التحقق',

  // ── Team
  '{name} — team progress': '{name} — تقدّم الفريق',
  'Where every new hire is in their onboarding.': 'أين وصل كل موظف جديد في رحلة التهيئة.',
  'Export CSV': 'تصدير CSV',
  'Export PDF': 'تصدير PDF',
  '{a}/{b} seats': '{a}/{b} مقعد',
  'Average completion': 'متوسط الإنجاز',
  'Waiting for grading': 'بانتظار التصحيح',

  // ── Profile
  'Your details, password, theme, language, email notifications and the devices signed in to your account.': 'بياناتك وكلمة المرور والمظهر واللغة وإشعارات البريد والأجهزة المسجّل دخولها إلى حسابك.',
  'Saved.': 'تم الحفظ.',
  'Personal details': 'البيانات الشخصية',
  'Full name': 'الاسم الكامل',
  Phone: 'الهاتف',
  'Job title': 'المسمى الوظيفي',
  Department: 'القسم',
  'Email (sign-in)': 'البريد (لتسجيل الدخول)',
  Role: 'الدور',
  'Last sign-in': 'آخر تسجيل دخول',
  'Your email and role are managed by your company admin.': 'يدير مدير شركتك بريدك ودورك.',
  'Your email and role are managed by the platform admin.': 'يدير مدير المنصة بريدك ودورك.',
  'Save changes': 'حفظ التغييرات',
  'Password changed. You’ve been signed out everywhere else.': 'تم تغيير كلمة المرور، وسُجّل خروجك من كل الأجهزة الأخرى.',
  'Change password': 'تغيير كلمة المرور',
  'Current password': 'كلمة المرور الحالية',
  'Changing your password signs out all your other devices.': 'تغيير كلمة المرور يسجّل خروجك من كل أجهزتك الأخرى.',
  'Changing…': 'جارٍ التغيير…',
  'Where you’re signed in': 'الأجهزة المسجّل دخولها',
  'Don’t recognise a device? Sign it out and change your password.': 'لا تعرف جهازًا؟ سجّل خروجه وغيّر كلمة المرور.',
  'Sign out other devices': 'تسجيل الخروج من الأجهزة الأخرى',
  'This device': 'هذا الجهاز',
  Remembered: 'محفوظ',
  'Signed in {date}': 'سجّل الدخول {date}',
  'active {x}': 'نشط {x}',
  Appearance: 'المظهر',
  Theme: 'السمة',
  Language: 'اللغة',
  Default: 'افتراضي',
  'Warm pastel': 'ألوان هادئة دافئة',
  Light: 'فاتح',
  'Crisp white': 'أبيض ناصع',
  Dark: 'داكن',
  'Easy on the eyes': 'مريح للعين',
  'Match device': 'حسب الجهاز',
  'Default or dark': 'افتراضي أو داكن',
  'Email notifications': 'إشعارات البريد',
  Saved: 'تم الحفظ',
  'You always see notifications under the bell. Choose which ones also come to': 'تظهر الإشعارات دائمًا تحت أيقونة الجرس. اختر ما يصلك منها أيضًا على',
  'Send me emails': 'أرسل لي رسائل بريد',
  'Turn off to get in-app notifications only': 'أوقفها لتصلك الإشعارات داخل المنصة فقط',
  'Grades & feedback': 'الدرجات والملاحظات',
  'When work is graded or returned for rework': 'عند تصحيح عمل أو إعادته للتعديل',
  'When you’re assigned a new course': 'عند إسناد دورة جديدة إليك',
  'Support replies': 'ردود الدعم',
  'When someone answers your question': 'عندما يرد أحد على سؤالك',
  'Due dates & reminders': 'المواعيد والتذكيرات',
  'Before a course or assignment is due, and when it’s overdue': 'قبل موعد استحقاق دورة أو مهمة، وعند تأخرها',
  'New work to review': 'أعمال جديدة للمراجعة',
  'New submissions and AI drafts ready': 'تسليمات جديدة ومسودات تصحيح جاهزة',
  'Employee questions': 'أسئلة الموظفين',
  'New questions and replies': 'أسئلة وردود جديدة',
  'Course assignments': 'إسناد الدورات',
  'When you’re added to a course': 'عند إضافتك إلى دورة',
  'Review reminders': 'تذكيرات المراجعة',
  'A daily nudge when submissions wait more than 2 days': 'تذكير يومي عندما تنتظر تسليمات أكثر من يومين',
  'Team updates': 'تحديثات الفريق',
  'Completed courses, shared progress reports, seats': 'الدورات المكتملة وتقارير التقدّم المشتركة والمقاعد',
  'New courses': 'دورات جديدة',
  'When a new course becomes available': 'عند إتاحة دورة جديدة',
  'When our team answers you': 'عندما يرد فريقنا عليك',
  'Overdue training': 'تدريب متأخر',
  'When an employee misses a course due date': 'عندما يتجاوز موظف موعد استحقاق دورة',
  'Support requests': 'طلبات الدعم',
  'New platform tickets and replies': 'تذاكر وردود جديدة على المنصة',
  Grading: 'التصحيح',
  'Submissions waiting for review': 'تسليمات بانتظار المراجعة',
  'Customer updates': 'تحديثات العملاء',
  'Seat limits and completions': 'حدود المقاعد والإنجازات',
};
